### PR TITLE
fix(progress): add RTL support to the progress component

### LINKED ISSUE #4908: [BUG] - Lack of RTL Support in Progress
### HeroUI Version

2.7.2

### Describe the bug

The Progress is filled from left-to-right even on RTL pages.

### Your Example Website or App

_No response_

### Steps to Reproduce the Bug or Issue

1. Go to [this page](https://storybook.heroui.com/?path=/docs/components-progress--docs&globals=locale:ar-AE)
2. Change the document direction to RTL: `<html dir="rtl">`
3. See the Progress bar direction.

### Expected behavior

I expect that the Progress bar fill from right-to-left if the page directions is RTL.

### Screenshots or Videos

Image

### Operating System Version

macOS

### Browser

Chrome

### PR DESCRIPTION
**Pull request by waleed-mobasher**
Closes #4908 

## 📝 Description

Add RTL support to the Progress component.

## ⛳️ Current behavior (updates)

The Progress component currently lacks support for right-to-left (RTL) direction, when the page direction is RTL the progress bar is filled from left-to-right as it behaves in LTR pages.

## 🚀 New behavior

Now the progress bar is filled from right-to-left if the page direction is RTL.

## 💣 Is this a breaking change (Yes/No):

No

## Summary by CodeRabbit

- **New Features**
	- Enhanced the progress component to support both right-to-left and left-to-right layouts, ensuring smooth and directionally accurate animations for a consistent user experience.

### CODE REVIEW

File: packages/core/theme/src/components/progress.ts [hunk 1]
```diff
@@ -97,7 +97,13 @@ const progress = tv(
       },
       isIndeterminate: {
         true: {
-          indicator: ["absolute", "w-full", "origin-left", "animate-indeterminate-bar"],
+          indicator: [
+            "absolute",
+            "w-full",
+            "rtl:origin-right",
+            "ltr:origin-left",
```
Comment (wingkwong) [inline packages/core/theme/src/components/progress.ts:104]: not required. please undo.

File: packages/core/theme/src/components/progress.ts [hunk 2]
```diff
@@ -27,8 +27,8 @@ const progress = tv(
       label: "",
       labelWrapper: "flex justify-between",
       value: "",
-      track: "z-0 relative bg-default-300/50 overflow-hidden",
-      indicator: "h-full",
+      track: "z-0 relative bg-default-300/50 overflow-hidden rtl:rotate-180",
+      indicator: "h-full rtl:origin-right ltr:origin-left",
```
Comment (wingkwong) [inline packages/core/theme/src/components/progress.ts:31]: not required. please undo.

File: .changeset/happy-kangaroos-thank.md [hunk 3]
```diff
@@ -0,0 +1,12 @@
...
+---
+
+These changes ensure that the progress bar behaves correctly in both LTR and RTL layouts, which is crucial for supporting languages that read from right to left (like Arabic, Hebrew, etc.). The transform origin points are particularly important for animations and transitions of the progress indicator.
+
+In the track class:
+Added rtl:rotate-180 which rotates the track 180 degrees when in RTL mode, ensuring correct direction
+
+In the indicator class added RTL-aware origin points:
+rtl:origin-right sets the transform origin to the right side in RTL mode.
+ltr:origin-left sets the transform origin to the left side in LTR (Left-to-Right) mode.
```
Comment (wingkwong) [inline .changeset/happy-kangaroos-thank.md:12]: just say 

```
add RTL support to progress (#4908)
```

**Review by wingkwong — CHANGES_REQUESTED** [review]

**Review by wingkwong — APPROVED** [review]

**Review by jrgarciadev — APPROVED** [review]
