### PR TITLE
fix(calendar): rtl navigation

### LINKED ISSUE #4541: Reversed Next and Previous Button Behavior in Persian Locale (fa) with NextUI Calendar
### NextUI Version

^2.6.11

### Describe the bug

Here’s a clear and concise description of your issue in English for the GitHub issue tracker:

Issue:
In the NextUI Calendar component, when the language/locale is set to Persian (fa), the behavior of the nextButton and prevButton is reversed. The "Next" button navigates to the previous month, and the "Previous" button navigates to the next month. This issue seems to be related to the RTL (right-to-left) layout handling in Persian calendars.

Expected Behavior:
The nextButton should navigate to the next month, and the prevButton should navigate to the previous month, regardless of the locale or direction (RTL/LTR).

### Your Example Website or App

_No response_

### Steps to Reproduce the Bug or Issue

**Steps to Reproduce the Bug or Issue:**  

1. Set the `locale` of the `Calendar` component to `fa` (Persian).  
2. Render the `Calendar` in an RTL (right-to-left) layout.  
3. Attempt to navigate to the next or previous month using the `nextButton` and `prevButton`.  
4. Observe that the `nextButton` navigates to the previous month and the `prevButton` navigates to the next month.  

This reversed behavior occurs specifically when the locale is set to Persian.

### Expected behavior

**Expected Behavior:**  
The `nextButton` should navigate to the next month, and the `prevButton` should navigate to the previous month, regardless of the locale or the RTL/LTR layout. This behavior should be consistent for all supported languages and layouts.

### Screenshots or Videos

_No response_

### Operating System Version

windows

### Browser

Chrome

### PR DESCRIPTION
**Pull request by MarufSharifi**
Closes #4541

## 📝 Description

Fixed the reverse behavior of calendar navigation in a RTL Layout.

## ⛳️ Current behavior (updates)

Reversed Next and Previous Button Behavior in Persian Locale (fa) with Calendar

## 🚀 New behavior

Fixed the reverse Next and Previous button behavior in RTL Calendar

## Summary by CodeRabbit

- **New Features**
  - Added localization support for text direction in the calendar component.
  - Implemented dynamic button rendering based on locale (LTR/RTL).
  - Introduced a new configuration variant for RTL support in the calendar component.

- **Bug Fixes**
  - Resolved navigation issues with the next and previous buttons in right-to-left (RTL) layouts, ensuring consistent functionality across various locales.

- **Chores**
  - Updated peer dependency for the `@heroui/theme` package to require a newer version.

### CODE REVIEW

**Review by wingkwong — CHANGES_REQUESTED** [review]
please add changeset

**Comment by MarufSharifi** [comment]
@wingkwong changeset added

File: packages/components/calendar/src/calendar-base.tsx [hunk 1]
```diff
@@ -55,20 +56,29 @@ export function CalendarBase(props: CalendarBaseProps) {
...
   const [direction, setDirection] = useState<number>(0);
 
+  const {direction: localeDirection} = useLocale();
+
   const currentMonth = state.visibleRange.start;
 
   const headers: React.ReactNode[] = [];
   const calendars: React.ReactNode[] = [];
 
+  const isLTR = localeDirection === "ltr";
```
Comment (wingkwong) [inline packages/components/calendar/src/calendar-base.tsx:66]: prefer `isRTL` instead to keep it consistent with other components.

File: packages/components/calendar/src/calendar-base.tsx [hunk 2]
```diff
@@ -55,20 +56,29 @@ export function CalendarBase(props: CalendarBaseProps) {
...
     headers.push(
       <Fragment key={`calendar-header-${i}`}>
         {i === 0 && (
           <Button
-            {...prevButtonProps}
-            onPress={chain(prevButtonProps.onPress, () => setDirection(-1))}
+            {...(isLTR ? prevButtonProps : nextButtonProps)}
+            className={
+              isLTR ? prevButtonProps?.["className"] : `${nextButtonProps?.["className"]} order-1`
+            }
```
Comment (wingkwong) [inline packages/components/calendar/src/calendar-base.tsx:78]: `className` shouldn't be defined here but in `theme` package.

File: packages/components/calendar/src/calendar-base.tsx [hunk 3]
```diff
@@ -81,8 +91,13 @@ export function CalendarBase(props: CalendarBaseProps) {
...
           <Button
-            {...nextButtonProps}
-            onPress={chain(nextButtonProps.onPress, () => setDirection(1))}
+            {...(isLTR ? nextButtonProps : prevButtonProps)}
+            className={
+              isLTR ? nextButtonProps?.["className"] : `${prevButtonProps?.["className"]} order-3`
+            }
+            onPress={chain(isLTR ? nextButtonProps.onPress : prevButtonProps.onPress, () =>
+              setDirection(1),
+            )}
```
Comment (wingkwong) [inline packages/components/calendar/src/calendar-base.tsx:100]: refer to above comments

**Review by wingkwong — CHANGES_REQUESTED** [review]
The changes involves a lot of ternary operators. Please make it cleaner.

**Comment by wingkwong** [comment]
@MarufSharifi what's left in this PR? If it's ready for review, please click re-request review. Thanks.

**Review by wingkwong — APPROVED** [review]

**Review by jrgarciadev — APPROVED** [review]
