### PR TITLE
fix(autocomplete): ensure focused item matches selected item after filter, selection

### LINKED ISSUE #5277: [BUG] - AutoComplete - focused item does not match selected item after filtering or setting default value
### HeroUI Version

2.7.8

### Describe the bug

When using the Autocomplete component, if an item is selected after filtering through the input or set via react-hook-form's default value, the focused item in the dropdown list does not match the selected item. Instead, focus always defaults to the first non-disabled item. This causes an issue where pressing Tab or arrow keys immediately changes the selection unexpectedly.

This issue does not occur when selecting an item directly without filtering — in that case, the focused item correctly matches the selected one.

### Your Example Website or App

https://www.heroui.com/docs/components/autocomplete

### Steps to Reproduce the Bug or Issue

- Use Autocomplete with a list of options.
- Set a default selected value via react-hook-form or by updating selectedKey, or filter the list by typing into the input.
- Focus the component by tabbing into it.
- Notice that the focused item starts at the first non-disabled option (even if it's not the selected one), causing the selection to change immediately when tabbing out or using keyboard navigation.

### Expected behavior

When an item is selected (either through input filtering or default value), the focused item in the list should match the selected item. Keyboard navigation should continue from the selected item, not from the first option.

### Screenshots or Videos

_No response_

### Operating System Version

Windows

### Browser

Chrome

### PR DESCRIPTION
**Pull request by KumJungMin**
Closes #5277 

## 📝 Description

- Fixes an issue in the Autocomplete component where the focused item in the dropdown did not respect a selected value (via filtering, defaultValue, or the selectedKey prop).

<br/>

## ⛳️ Current behavior (updates)

- On first focus (e.g., via Tab), the dropdown always focuses the first non-disabled item, even if another item is already selected.
- Immediate keyboard navigation (Tab or arrow keys) can unexpectedly change the user’s selection away from their chosen item.

https://github.com/user-attachments/assets/5e44e80f-1c77-4370-a000-f6a28024331d

_< video: the dropdown always focuses the first non-disabled item. (tab mode) >_

<br/>

## 🚀 New behavior

- When the component receives focus and a valid item is selected, focus is set to that selected item.
- If the selected item is missing or disabled, focus falls back to the first non-disabled item.
- Keyboard navigation now begins from the contextually correct item, improving accessibility and usability.

https://github.com/user-attachments/assets/0cafcafc-2280-477f-b0de-cb6876c020bb

_< video: focus is set to that selected item.(tab mode) >_

<br/>

https://github.com/user-attachments/assets/b73a437c-d88a-4981-8e94-3dea4966dd32

_< video: focus is set to that selected item. (props change mode) >_

<br/>

## 💣 Is this a breaking change (Yes/No):

- No
: This change corrects unintended focus behavior and aligns the component with expected accessibility patterns without impacting existing integrations.

<br/>

## 📝 Additional Information

- The fix updates the useEffect hook dependencies (state.collection, state.disabledKeys, state.selectedKey) and calls state.selectionManager.setFocusedKey(keyToFocus) to apply the correct focus.
- Scroll synchronization to the focused item when the popover opens is not included in this PR, as it was deemed out of scope for this issue.

## Summary by CodeRabbit

- **Bug Fixes**
	- Improved focus behavior in autocomplete so that the currently selected item is focused when available and enabled, enhancing usability and navigation.
- **Tests**
	- Added new tests to verify focused item behavior in various selection and interaction scenarios, ensuring consistent user experience.

### CODE REVIEW

File: packages/components/autocomplete/src/use-autocomplete.ts [hunk 1]
```diff
@@ -339,15 +339,26 @@ export function useAutocomplete<T extends object>(originalProps: UseAutocomplete
...
   }, [inputRef.current]);
 
-  // focus first non-disabled item
+  // focus selected item or first non-disabled item
   useEffect(() => {
-    let key = state.collection.getFirstKey();
-
-    while (key && state.disabledKeys.has(key)) {
-      key = state.collection.getKeyAfter(key);
+    let keyToFocus;
```
Comment (wingkwong) [inline packages/components/autocomplete/src/use-autocomplete.ts:344]:
```tsx
let keyToFocus: Key | null;
```

File: packages/components/autocomplete/src/use-autocomplete.ts [hunk 2]
```diff
@@ -339,15 +339,26 @@ export function useAutocomplete<T extends object>(originalProps: UseAutocomplete
...
+
+    if (
+      state.selectedKey != null &&
```
Comment (wingkwong) [inline packages/components/autocomplete/src/use-autocomplete.ts:347]:
```tsx
state.selectedKey !== null
```

**Review by wingkwong — CHANGES_REQUESTED** [review]
1. please add a changeset
2. please include a test

File: packages/components/autocomplete/src/use-autocomplete.ts (hunk 1 above)
Comment (KumJungMin) [reply packages/components/autocomplete/src/use-autocomplete.ts]: - thank you for suggestion :) (updated: https://github.com/heroui-inc/heroui/pull/5290/commits/eacecb76462fbe8e50dc5aad46db480d8f6c0cf0)

File: packages/components/autocomplete/src/use-autocomplete.ts (hunk 2 above)
Comment (KumJungMin) [reply packages/components/autocomplete/src/use-autocomplete.ts]: - thank you for suggestion 😄  (updated: https://github.com/heroui-inc/heroui/pull/5290/commits/eacecb76462fbe8e50dc5aad46db480d8f6c0cf0)

**Comment by KumJungMin** [comment]
> 1. please add a changeset
> 2. please include a test

---

1I've added a changeset: (https://github.com/heroui-inc/heroui/pull/5290/commits/f4784db3840bd780fdcf1c152da3b44929061888)
2.I've also included a test :) : (https://github.com/heroui-inc/heroui/pull/5290/commits/e50f1ec7e4cdc82e3d835cc1b14cf115b97cd33d)

File: .changeset/clean-seahorses-cheat.md [hunk 3]
```diff
@@ -0,0 +1,5 @@
+---
+"@heroui/autocomplete": major
```
Comment (wingkwong) [inline .changeset/clean-seahorses-cheat.md:2]: `major` -> `patch`.

File: .changeset/clean-seahorses-cheat.md [hunk 4]
```diff
@@ -0,0 +1,5 @@
...
+---
+
+ensure focused item matches selected item after filter, selection
```
Comment (wingkwong) [inline .changeset/clean-seahorses-cheat.md:5]: include issue number. i.e.

```
ensure focused item matches selected item after filter, selection (#5277)
```

File: packages/components/autocomplete/src/use-autocomplete.ts [hunk 5]
```diff
@@ -339,7 +339,10 @@ export function useAutocomplete<T extends object>(originalProps: UseAutocomplete
     }
   }, [inputRef.current]);
 
-  // focus selected item or first non-disabled item
+  // Ensure the focused item in the dropdown correctly reflects the
+  // selected key when the component mounts or relevant state changes.
+  // This fixes a bug where focus incorrectly defaulted to the first item
+  // when a value was pre-selected (e.g., via defaultValue or filtering).
```
Comment (wingkwong) [inline packages/components/autocomplete/src/use-autocomplete.ts:345]: remove these 2 lines

**Review by wingkwong — CHANGES_REQUESTED** [review]

File: .changeset/clean-seahorses-cheat.md (hunk 4 above)
Comment (KumJungMin) [reply .changeset/clean-seahorses-cheat.md]: - I've added issue number :) (https://github.com/heroui-inc/heroui/pull/5290/commits/1fa4119758ac98404e550146fc1244f1abb73c63)

File: packages/components/autocomplete/src/use-autocomplete.ts (hunk 5 above)
Comment (KumJungMin) [reply packages/components/autocomplete/src/use-autocomplete.ts]: - I've removed these 2 lines (https://github.com/heroui-inc/heroui/pull/5290/commits/68e3335e307b897a26d0c55426f9c25fab1706d1)

**Review by jrgarciadev — APPROVED** [review]
