### PR TITLE
fix(toast): toast should appear above overlay and adding regionProps to ToastProvider

### LINKED ISSUE #4898: [BUG] - Toast is hidden under drawer / modal
### HeroUI Version

2.7.2

### Describe the bug

Toast notifications cannot be used with Drawer components since the drawer mask and drawer itself are always rendered above the toast messages. I've tried applying a larger z-index, but this doesn't solve the issue - the drawer still overlays the toast.

code to reproduce:
```tsx
    <ToastProvider
        placement="bottom-left"
        toastOffset={30}
        toastProps={{
          shouldShowTimeoutProgess: true,
          radius: 'lg',
          classNames: {
            base: 'z-[1000]'
          }
        }}
      />



import {
  Button,
  Drawer,
  DrawerBody,
  DrawerContent,
  addToast,
  useDisclosure
} from '@heroui/react'

export default function SandboxPage() {
  const { isOpen, onOpen, onOpenChange } = useDisclosure()
  return (
    <div className="p-8">
      <Drawer isOpen={isOpen} onOpenChange={onOpenChange}>
        <DrawerContent>
          <DrawerBody className="flex flex-col justify-center items-center">
            <Button
              onPress={() =>
                addToast({
                  title: 'Hello World',
                  description: 'This is a toast message',
                  color: 'success'
                })
              }
            >
              Add Toast
            </Button>
          </DrawerBody>
        </DrawerContent>
      </Drawer>
      <Button onPress={onOpen}>Open Drawer</Button>
    </div>
  )
}
```

### Your Example Website or App

_No response_

### Steps to Reproduce the Bug or Issue

1. Click on Open drawer
2. Click on Add toast

### Expected behavior

The Toast should be always visible and on top of any other component 

### Screenshots or Videos

Image

### Operating System Version

macOS

### Browser

Chrome

### PR DESCRIPTION
**Pull request by macci001**
Closes #4898 

## 📝 Description

This is the PR https://github.com/heroui-inc/heroui/pull/4919 without breaking changes

## Summary by CodeRabbit

- **New Features**
  - Toast notifications now consistently appear above modals for improved visual priority.
  - Enhanced customization options allow tailored styling for toast displays.
  - A new overlay demonstration showcases integrated toast behavior with modals and drawers.

- **Documentation**
  - Updated accessibility and API details for the Toast component, highlighting new customization properties including `regionProps` and `classNames`.

### CODE REVIEW

File: packages/components/toast/src/toast-region.tsx [hunk 1]
```diff
@@ -41,6 +51,8 @@ export function ToastRegion<T extends ToastProps>({
     [disableAnimation],
   );
 
+  const baseStyles = clsx(className, classNames?.base);
```
Comment (wingkwong) [inline packages/components/toast/src/toast-region.tsx:54]: just keep it same as other components.

```tsx
const baseStyles = clsx(classNames?.base, className);
```

File: packages/components/toast/src/toast-region.tsx [hunk 2]
```diff
@@ -65,7 +77,7 @@ export function ToastRegion<T extends ToastProps>({
     <div
       {...mergeProps(regionProps, hoverProps)}
       ref={ref}
-      className={slots.base()}
+      className={slots.base({class: clsx(baseStyles)})}
```
Comment (wingkwong) [inline packages/components/toast/src/toast-region.tsx:80]: `clsx` is unnecessary here. just do

```tsx
className: slots.base({class: baseStyles}),
```

**Review by wingkwong — CHANGES_REQUESTED** [review]

File: packages/components/toast/src/toast-region.tsx (hunk 1 above)
Comment (macci001) [reply packages/components/toast/src/toast-region.tsx]: Sure, updated in latest commit

File: packages/components/toast/src/toast-region.tsx (hunk 2 above)
Comment (macci001) [reply packages/components/toast/src/toast-region.tsx]: Thanks, updated in latest commit

**Review by wingkwong — APPROVED** [review]

**Review by jrgarciadev — APPROVED** [review]
Thanks! @macci001

File: packages/components/toast/src/toast-provider.tsx [hunk 3]
```diff
@@ -73,5 +76,6 @@ export const closeAll = () => {
 
   keys.map((key) => {
     globalToastQueue?.close(key);
+    globalToastQueue?.remove(key);
```
Comment (davidaragundy) [inline packages/components/toast/src/toast-provider.tsx:79]: this prop does not exist?

Comment (jrgarciadev) [reply packages/components/toast/src/toast-provider.tsx:79]: Thanks! @davidaragundy , fixed https://github.com/heroui-inc/heroui/commit/41084ac972f37af5686bf0ab509b34119edbe370
