### PR TITLE
fix(slider): prevent NaN error for equal min / max values

### LINKED ISSUE #5014: [BUG] - Range slider breaks when min and max are the same
### HeroUI Version

@heroui/slider@2.4.12

### Describe the bug

If the values ​​are the same, it starts acting somehow inadequately, writing Invalid end: NaN

https://codesandbox.io/p/devbox/intelligent-pike-wwcmnw

### Your Example Website or App

_No response_

### Steps to Reproduce the Bug or Issue

1. Set minValue={100}
2. Set maxValue={100}
3. Try dragging

### Expected behavior

Fix the error and make it possible to set min max to be the same

### Screenshots or Videos

_No response_

### Operating System Version

macOS

### Browser

Chrome

### PR DESCRIPTION
**Pull request by kaishuige**
Closes #5014 

## 📝 Description

Fixed an issue where the slider component would display "Invalid end: NaN" when minimum and maximum values are the same. The fix maintains slider interactivity while preventing NaN calculations.

## ⛳️ Current behavior (updates)

No error will be reported. NAN will not be displayed. Fixed values will be displayed. You can't slide and click.

## 🚀 New behavior

NO

## 💣 Is this a breaking change (Yes/No):

NO

## Summary by CodeRabbit

- **Bug Fixes**
	- Enhanced the slider component to correctly handle scenarios where the minimum and maximum values are the same. The slider now reliably displays the fixed value, prevents “NaN” outputs, and maintains proper accessibility and interaction behavior.
- **Tests**
	- Added a new test case to ensure the slider behaves correctly when minimum and maximum values are identical.

### CODE REVIEW

**Review by wingkwong — CHANGES_REQUESTED** [review]
1. please add changeset.
2. I think we don't need to change slider-thumb, and use-slider-thumb at all. `NaN` is caused from RA side since supposedly min and max shouldn't be same. So my idea is that you can simply create a new variable called `stateValues` in `use-slider.ts`. If it is a fixed value, then remove filter out all NaN values, else take state.values. Then replace all existing `state.values` with stateValue. In this case, it would be much cleaner. Also you may return after L420 if it is a fixed value.

**Comment by kaishuige** [comment]
OK, I'll try it later.

File: packages/components/slider/src/use-slider.ts [hunk 1]
```diff
@@ -270,6 +297,7 @@ export function useSlider(originalProps: UseSliderProps) {
       "data-orientation": state.orientation,
       "data-slot": "base",
       "data-hover": isHovered,
+      "data-fixed-value": isFixedValue,
```
Comment (wingkwong) [inline packages/components/slider/src/use-slider.ts:300]: not necessary

File: packages/components/slider/src/use-slider.ts [hunk 2]
```diff
@@ -248,19 +250,44 @@ export function useSlider(originalProps: UseSliderProps) {
...
+    if (isFixedValue) return 0;
+
+    return state.getThumbPercent(index);
+  };
+
+  const getValuePercent = (value: number) => {
+    if (isFixedValue) return 0;
+
+    return state.getValuePercent(value);
+  };
```
Comment (wingkwong) [inline packages/components/slider/src/use-slider.ts:263]: not required if you don't include L273 - L276.

File: packages/components/slider/src/use-slider.ts [hunk 3]
```diff
@@ -248,19 +250,44 @@ export function useSlider(originalProps: UseSliderProps) {
...
+    if (isFixedValue) {
+      return state.values.filter((val) => !Number.isNaN(val));
+    }
+
+    return state.values;
+  }, [isFixedValue, state.values]);
+
+  if (isFixedValue && stateValues.length === 0) {
+    stateValues.push(minValue);
+  }
```
Comment (wingkwong) [inline packages/components/slider/src/use-slider.ts:275]: not required.

File: packages/components/slider/src/use-slider.ts [hunk 4]
```diff
@@ -248,19 +250,44 @@ export function useSlider(originalProps: UseSliderProps) {
...
-    state.values.length > 1
-      ? state.getThumbPercent(0)
+    stateValues.length > 1
+      ? getThumbPercent(0)
       : fillOffset !== undefined
-      ? state.getValuePercent(fillOffset)
+      ? getValuePercent(fillOffset)
       : 0,
-    state.getThumbPercent(state.values.length - 1),
+    getThumbPercent(stateValues.length - 1),
```
Comment (wingkwong) [inline packages/components/slider/src/use-slider.ts:283]: still use `state.getThumbPercent`

File: packages/components/slider/src/use-slider.ts [hunk 5]
```diff
@@ -248,19 +250,44 @@ export function useSlider(originalProps: UseSliderProps) {
...
+  }
+
   const [startOffset, endOffset] = [
-    state.values.length > 1
-      ? state.getThumbPercent(0)
+    stateValues.length > 1
+      ? getThumbPercent(0)
       : fillOffset !== undefined
-      ? state.getValuePercent(fillOffset)
+      ? getValuePercent(fillOffset)
```
Comment (wingkwong) [inline packages/components/slider/src/use-slider.ts:281]: still use `state.getValuePercent`

File: packages/components/slider/src/use-slider.ts [hunk 6]
```diff
@@ -248,19 +250,44 @@ export function useSlider(originalProps: UseSliderProps) {
...
+
+  if (isFixedValue && stateValues.length === 0) {
+    stateValues.push(minValue);
+  }
+
   const [startOffset, endOffset] = [
-    state.values.length > 1
-      ? state.getThumbPercent(0)
+    stateValues.length > 1
+      ? getThumbPercent(0)
```
Comment (wingkwong) [inline packages/components/slider/src/use-slider.ts:279]: still use `state.getThumbPercent`

File: packages/components/slider/src/use-slider.ts [hunk 7]
```diff
@@ -248,19 +250,44 @@ export function useSlider(originalProps: UseSliderProps) {
...
 
-  const value =
-    state.values.length === 1
-      ? numberFormatter.format(state.values[0])
-      : numberFormatter.formatRange(state.values[0], state.values[state.values.length - 1]);
+  const value = isFixedValue
+    ? numberFormatter.format(minValue)
+    : stateValues.length === 1
+    ? numberFormatter.format(stateValues[0])
+    : numberFormatter.formatRange(stateValues[0], stateValues[stateValues.length - 1]);
```
Comment (wingkwong) [inline packages/components/slider/src/use-slider.ts:290]: rollback to original code

File: packages/components/slider/src/use-slider.ts [hunk 8]
```diff
@@ -360,13 +388,14 @@ export function useSlider(originalProps: UseSliderProps) {
...
       renderThumb,
+      isFixedValue,
       formatOptions: tooltipValueFormatOptions,
       className: slots.thumb({class: classNames?.thumb}),
     } as SliderThumbProps;
   };
 
   const getStepProps = (index: number) => {
-    const percent = state.getValuePercent(index * step + minValue);
+    const percent = isFixedValue ? 0 : state.getValuePercent(index * step + minValue);
```
Comment (wingkwong) [inline packages/components/slider/src/use-slider.ts:398]: not required

File: packages/components/slider/src/use-slider.ts [hunk 9]
```diff
@@ -379,7 +408,7 @@ export function useSlider(originalProps: UseSliderProps) {
   };
 
   const getMarkProps = (mark: SliderStepMark) => {
-    const percent = state.getValuePercent(mark.value);
+    const percent = isFixedValue ? 0 : state.getValuePercent(mark.value);
```
Comment (wingkwong) [inline packages/components/slider/src/use-slider.ts:411]: not required

File: packages/components/slider/src/use-slider.ts [hunk 10]
```diff
@@ -394,12 +423,18 @@ export function useSlider(originalProps: UseSliderProps) {
       onMouseDown: (e: React.MouseEvent) => e.stopPropagation(),
       onPointerDown: (e: React.PointerEvent) => e.stopPropagation(),
       onClick: (e: any) => {
+        if (isFixedValue) {
+          e.stopPropagation();
+
+          return;
+        }
```
Comment (wingkwong) [inline packages/components/slider/src/use-slider.ts:430]: return after L432.

File: packages/components/slider/__tests__/slider.test.tsx [hunk 11]
```diff
@@ -64,6 +64,26 @@ describe("Slider", () => {
...
+    );
+
+    const slider = getByRole("slider");
+    const group = getByRole("group");
+    const output = getByRole("status");
+
+    expect(slider).toHaveProperty("min", "10");
+    expect(slider).toHaveProperty("max", "10");
+
+    expect(group).toHaveAttribute("data-fixed-value", "true");
```
Comment (wingkwong) [inline packages/components/slider/__tests__/slider.test.tsx:79]: not need to check this.

File: packages/components/slider/src/use-slider.ts [hunk 12]
```diff
@@ -173,6 +173,8 @@ export function useSlider(originalProps: UseSliderProps) {
     ...otherProps
   } = props;
 
+  const isFixedValue = minValue === maxValue;
```
Comment (wingkwong) [inline packages/components/slider/src/use-slider.ts:176]: probably throw a warning in console if `isFixedValue` is true

**Review by wingkwong — CHANGES_REQUESTED** [review]

File: packages/components/slider/src/use-slider.ts (hunk 12 above)
Comment (kaishuige) [reply packages/components/slider/src/use-slider.ts:176]: Does it mean that you only need to control the warning?

Comment (wingkwong) [reply packages/components/slider/src/use-slider.ts:176]: use `warn` from `@heroui/shared-utils` to tell users minValue and maxValue shouldn't be same

**Comment by kaishuige** [comment]
It's done. I understand what you mean.

File: packages/components/slider/__tests__/slider.test.tsx [hunk 13]
```diff
@@ -64,6 +64,21 @@ describe("Slider", () => {
...
+
+    const slider = getByRole("slider");
+    const output = getByRole("status");
+
+    expect(slider).not.toHaveAttribute("disabled");
+
+    expect(slider).toHaveAttribute("aria-valuetext", "10");
+    expect(output).toHaveTextContent("10");
+    expect(output).not.toHaveTextContent("NaN");
+  });
```
Comment (wingkwong) [inline packages/components/slider/__tests__/slider.test.tsx:80]: This test can pass in canary branch, which means this test case doesn't test the original issue. Ideally it should fail in canary branch and pass in your PR branch.

File: packages/components/slider/src/use-slider.ts (hunk 7 above)
Comment (wingkwong) [reply packages/components/slider/src/use-slider.ts:274]: unnecessary change here

**Review by wingkwong — CHANGES_REQUESTED** [review]

File: packages/components/slider/__tests__/slider.test.tsx (hunk 13 above)
Comment (kaishuige) [reply packages/components/slider/__tests__/slider.test.tsx]: Sorry, I don't quite understand what you said. This is my idea and solution.

1. Modify the clampValue function to ensure that it returns minValue when isFixedValue is true. 
3. When isFixedValue is true, directly set validatedValue to minValue. 
3. Provide an empty callback function when isFixedValue is true. 
4.  5. When isFixedValue is true, set defaultValue to minValue.

Then I updated the test case.
If you have a better way, you can modify it on my basis.

Comment (wingkwong) [reply packages/components/slider/__tests__/slider.test.tsx]: The test case you add should fail without your changes. If it is passing, that means your test case doesn't catch the reported issue.

Comment (kaishuige) [reply packages/components/slider/__tests__/slider.test.tsx]: I have revised it according to my ideas. You can have a look.

File: packages/components/slider/src/use-slider.ts [hunk 14]
```diff
@@ -185,31 +191,37 @@ export function useSlider(originalProps: UseSliderProps) {
...
 
   const clampValue = useCallback(
-    (valueToClamp: number) => Math.min(Math.max(valueToClamp, minValue), maxValue),
-    [minValue, maxValue],
+    (valueToClamp: number) => {
+      if (isFixedValue) return minValue;
+
+      return Math.min(Math.max(valueToClamp, minValue), maxValue);
+    },
+    [minValue, maxValue, isFixedValue],
```
Comment (wingkwong) [inline packages/components/slider/src/use-slider.ts:199]: Undo it. `clampValue` is called from `validatedValue`, where you return `minValue` if `isFixedValue` is `true`. Hence, the change you added won't take any effect.

File: packages/components/slider/src/use-slider.ts [hunk 15]
```diff
@@ -185,31 +191,37 @@ export function useSlider(originalProps: UseSliderProps) {
...
   );
 
   const validatedValue = useMemo(() => {
+    if (isFixedValue) return minValue;
```
Comment (wingkwong) [inline packages/components/slider/src/use-slider.ts:203]: add a new line after it

File: packages/components/slider/src/use-slider.ts [hunk 16]
```diff
@@ -185,31 +191,37 @@ export function useSlider(originalProps: UseSliderProps) {
...
     isDisabled: originalProps?.isDisabled ?? false,
     orientation,
     step,
     minValue,
     maxValue,
     numberFormatter,
-    onChange,
-    onChangeEnd,
+    onChange: isFixedValue ? () => {} : onChange,
+    onChangeEnd: isFixedValue ? () => {} : onChangeEnd,
```
Comment (wingkwong) [inline packages/components/slider/src/use-slider.ts:224]: undo

File: .changeset/fix-slider-nan.md [hunk 17]
```diff
@@ -0,0 +1,5 @@
+---
+"@heroui/slider": patch
+---
+
+fix: handle slider component NaN values when min and max are the same value
```
Comment (wingkwong) [inline .changeset/fix-slider-nan.md:5]:
```
fixed slider component NaN values when min and max are the same value  (#5014)
```

File: packages/components/slider/__tests__/slider.test.tsx [hunk 18]
```diff
@@ -64,6 +64,35 @@ describe("Slider", () => {
     expect(slider).toHaveProperty("max", "20");
   });
 
+  it("should handle fixed value when minValue and maxValue are the same", async () => {
+    const onChangeMock = jest.fn();
+
+    const {getByRole} = render(
+      <Slider
+        aria-label="Fixed Slider"
+        label="Fixed Value"
```
Comment (wingkwong) [inline packages/components/slider/__tests__/slider.test.tsx:73]: should be same

File: packages/components/slider/__tests__/slider.test.tsx [hunk 19]
```diff
@@ -64,6 +64,35 @@ describe("Slider", () => {
...
+        maxValue={10}
+        minValue={10}
+        onChange={onChangeMock}
```
Comment (wingkwong) [inline packages/components/slider/__tests__/slider.test.tsx:76]: no need to test onChange

File: packages/components/slider/__tests__/slider.test.tsx [hunk 20]
```diff
@@ -64,6 +64,35 @@ describe("Slider", () => {
...
+      />,
+    );
+
+    const slider = getByRole("slider");
+    const output = getByRole("status");
+
+    expect(slider).not.toHaveAttribute("disabled");
```
Comment (wingkwong) [inline packages/components/slider/__tests__/slider.test.tsx:83]: no need to test disabled

**Review by wingkwong — CHANGES_REQUESTED** [review]

File: packages/components/slider/__tests__/slider.test.tsx (hunk 20 above)
Comment (kaishuige) [reply packages/components/slider/__tests__/slider.test.tsx]: It's all taken care of. Do we need a new pr?

File: packages/components/slider/src/use-slider.ts [hunk 21]
```diff
@@ -185,23 +191,28 @@ export function useSlider(originalProps: UseSliderProps) {
...
     }
 
     return clampValue(valueProp);
-  }, [valueProp, clampValue]);
+  }, [valueProp, clampValue, isFixedValue, minValue]);
 
   const state = useSliderState({
     ...otherProps,
     value: validatedValue,
+    defaultValue: otherProps.defaultValue,
```
Comment (wingkwong) [inline packages/components/slider/src/use-slider.ts:215]: doesn't it include in L213 already?

**Review by wingkwong — CHANGES_REQUESTED** [review]
